CREATE SEQUENCE IF NOT EXISTS hibernate_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE order_details
(
    id             BIGINT NOT NULL,
    user_id        BIGINT,
    product_id     BIGINT NOT NULL,
    order_price    DOUBLE PRECISION,
    order_quantity INTEGER,
    adding_to      TIMESTAMP WITHOUT TIME ZONE,
    is_ordered     BOOLEAN,
    CONSTRAINT pk_orderdetails PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id               BIGINT,
    order_full_name       VARCHAR(255),
    order_phone           VARCHAR(255),
    order_email           VARCHAR(255),
    order_country         VARCHAR(255),
    order_city            VARCHAR(255),
    order_ship_address    VARCHAR(255),
    order_zip             VARCHAR(255),
    order_date            TIMESTAMP WITHOUT TIME ZONE,
    is_order_shipped      BOOLEAN,
    order_tracking_number VARCHAR(255),
    order_price           DOUBLE PRECISION,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE orders_to_order_details_map
(
    order_details_id BIGINT NOT NULL,
    order_id         BIGINT NOT NULL
);

CREATE TABLE product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    price       DOUBLE PRECISION,
    description VARCHAR(255),
    amount      BIGINT,
    adding_to   TIMESTAMP WITHOUT TIME ZONE,
    picture     VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (id)
);

CREATE TABLE roles
(
    user_id BIGINT NOT NULL,
    roles   VARCHAR(255)
);

CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255),
    email         VARCHAR(255),
    password      VARCHAR(255),
    enabled       BOOLEAN,
    auth_provider VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE order_details
    ADD CONSTRAINT FK_ORDERDETAILS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE order_details
    ADD CONSTRAINT FK_ORDERDETAILS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER FOREIGN KEY (user_id) REFERENCES users (user_id);

ALTER TABLE orders_to_order_details_map
    ADD CONSTRAINT fk_ordtoorddetmap_on_order FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE orders_to_order_details_map
    ADD CONSTRAINT fk_ordtoorddetmap_on_order_details FOREIGN KEY (order_details_id) REFERENCES order_details (id);

ALTER TABLE roles
    ADD CONSTRAINT fk_roles_on_user FOREIGN KEY (user_id) REFERENCES users (user_id);